[/Script/UnrealEd.ProjectPackagingSettings]
; Include current and future maps from the level menu's folder and their dependencies.
bCookAll=False
bCookMapsOnly=False
+DirectoriesToAlwaysCook=(Path="/Game/Maps")
+MapsToCook=(FilePath="/Game/Maps/LevelMenu")
+DirectoriesToAlwaysCook=(Path="/Game/Materials")
+MapsToCook=(FilePath="/Game/Maps/PortalLab")
+MapsToCook=(FilePath="/Game/Maps/PortalGunLab")
+MapsToCook=(FilePath="/Game/Maps/PortalPuzzle")
+MapsToCook=(FilePath="/Game/Maps/TinyHarvest")
+MapsToCook=(FilePath="/Game/Maps/PortalFoundationLab")
+MapsToCook=(FilePath="/Game/Maps/PortalTraversalLab")
+DirectoriesToAlwaysCook=(Path="/Game/Characters/Mannequins/Anims/Unarmed")

[/Script/EngineSettings.GeneralProjectSettings]
ProjectVersion=2.0.1
ProjectName=PortalPrototype

